highlighter: true
permalink: "/:title"
markdown: kramdown
#highlighter: rouge
incremental: false
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
gems:
- jekyll-mermaid
mermaid:
  src: './static/js/mermaid.min.js'
